// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("discord")
	ScopeName = "github.com/zmoog/flexo/receiver/discordreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
